name: CI
on:
  pull_request:
    branches:
      - "main"
  merge_group:
  workflow_dispatch:

jobs:
  ios-build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - uses: subosito/flutter-action@v2
        with:
          channel: "beta"

      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Preprocess
        run: python3 preprocess-ios.py
        
      - name: Podfile
        run: |
          cd ios
          # rm Podfile.lock
          flutter clean
          flutter pub get
          pod install
          pod update
          cd ..

      - name: Build
        run: |
          flutter build ios --release --no-codesign
          mkdir -p Payload
          mv ./build/ios/iphoneos/Runner.app Payload
          zip -r -y Payload.zip Payload/Runner.app
          mv Payload.zip Payload.ipa

      - name: Upload IPA
        uses: actions/upload-artifact@v2
        with:
          name: ipa-build
          path: Payload.ipa
